name: stellar
version: 0.4.0

description: Stellar client library for the Dart language.
author: Jeff Lee <jspschool@gmail.com>
homepage: https://github.com/jspschool/dart-stellar-sdk

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  convert: ^2.1.1
  crypto: ^2.1.3
  eventsource: ^0.2.2
  fixnum: ^0.10.11
  http: ^0.12.0+3
  tweetnacl: ^0.3.2

dev_dependencies:
  test: ^1.0.0
  mockito: ^3.0.0
